In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/diabetes1.csv') #data about how you have uploaded data,click 3 dots in files,copy path in bracetes
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1,85.0,66.0,NaN,0.0,26.6,0.351,31.0,0.0
2,8,NaN,NaN,0.0,0.0,23.3,0.672,32.0,1.0
3,1,89.0,66.0,23.0,94.0,NaN,0.167,21.0,0.0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1.0

In [3]:
df.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50.0,1.0
1,1,85.0,66.0,NaN,0.0,26.6,0.351,31.0,0.0

In [4]:
df.shape

(768, 9)

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,767.000000,765.000000,765.000000,763.000000,764.000000,767.000000,766.000000,767.000000
mean,3.845052,120.813559,69.201307,20.579085,80.213630,31.981937,0.471726,33.246736,0.348110
std,3.369578,31.914588,19.230790,15.945936,115.476033,7.892066,0.331519,11.774924,0.476682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243500,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,36.000000,32.000000,0.371000,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.000000,128.500000,36.600000,0.626500,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
df.isna()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False
2,False,True,True,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,False,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,False,False,False,False,False,False
767,False,False,False,False,False,False,False,False,False

In [7]:
df.isna().sum().sort_values()

Pregnancies                 0
Glucose                     1
DiabetesPedigreeFunction    1
Outcome                     1
Age                         2
SkinThickness               3
BloodPressure               3
BMI                         4
Insulin                     5
dtype: int64